import { test, expect } from '@playwright/test';

/**
 * API-level coverage of /submit-form/ and /validate-email/, run from INSIDE
 * a real browser page session instead of a standalone HTTP client.
 *
 * Why this file exists: the production site sits behind CloudFront with an
 * edge-level bot/WAF rule that returns a hard 403 ("Generated by cloudfront")
 * to requests that don't look like they came from a real browser -- this
 * blocks Postman, Newman, and raw curl/requests alike, regardless of
 * matching headers, in testing done for this assessment. See
 * postman/collection.json's description and BUG-REPORT.md for the evidence
 * and what was tried. The assignment brief explicitly names this as an
 * anticipated scenario and suggests Playwright's request context as the
 * fallback ("use Playwright's APIRequest context").
 *
 * This file goes one step further than APIRequestContext: it fires the
 * actual fetch() calls via page.evaluate(), so they execute inside the
 * loaded page's real browser network stack (genuine TLS fingerprint, the
 * page's own session/cookies, same-origin headers) -- indistinguishable
 * from what a real user's browser sends when the SPA itself calls these
 * endpoints. This is how the findings in BUG-06 through BUG-09 were
 * originally confirmed live.
 *
 * Safety: API-01 and API-04 (below) POST a full valid submission and would
 * create a REAL lead in the CRM if run against the live endpoint. Per the
 * assignment's own instruction -- "for your automated tests, stub the
 * network call... so CI runs don't create real CRM leads" -- both are
 * stubbed here via page.route(), fulfilling with the exact response shape
 * captured from the real endpoint during exploratory testing. No run of
 * this file ever creates a lead.
 *
 * This means API-01/04 are locked-in contract checks, not live
 * re-verification -- the live confirmation (including BUG-06: a 200 and a
 * real lead ID with no consent field sent) was captured once, by hand,
 * during exploratory testing and is the evidence documented in
 * BUG-REPORT.md and postman/collection.json. If BUG-06 ever needs
 * re-confirming against production, that's a deliberate manual step (see
 * BUG-REPORT.md), not something this automated suite does on its own.
 *
 * Everything else here (API-02/03/06/07/08's non-mutating scenarios) is
 * read-only or 502s before a lead would be created, so those run for real
 * against production -- that's what proves the CloudFront bypass works and
 * is how BUG-07/08/09 were originally confirmed live.
 */

type SubmitFields = Record<string, string>;

const baselineFields = (): SubmitFields => ({
  FirstName: 'QA Candidate',
  LastName: 'Karina Zhdanova',
  Email: 'karina.zhd+test@gmail.com',
  PostalCode: '80202',
  Phone: '3035550100',
  PreferredContactType: 'Email',
  PreferredTimeOfDay: 'Flexible',
  PreferredDays: 'Flexible',
  termsAgreement: 'true',
  smsOptIn: 'false',
});

/**
 * Fires the exact wire-format request the live SPA sends: Content-Type
 * claims x-www-form-urlencoded, but the body is actually JSON with a
 * `values` key holding a URL-encoded field string (see InquiryPage.ts's
 * class docstring / BUG-REPORT.md notes for how this was captured).
 * Runs inside the page via page.evaluate so it carries a real browser
 * fingerprint and passes the CloudFront edge check.
 */
async function submitFormViaFetch(
  page: import('@playwright/test').Page,
  fields: SubmitFields
): Promise<{ status: number; bodyText: string }> {
  return page.evaluate(async (fieldsArg) => {
    const encoded = Object.entries(fieldsArg)
      .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
      .join('&');
    const res = await fetch('/submit-form/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: JSON.stringify({ values: encoded, form: 'SHORT_FORM' }),
    });
    return { status: res.status, bodyText: await res.text() };
  }, fields);
}

async function validateEmailViaFetch(
  page: import('@playwright/test').Page,
  email: string
): Promise<{ status: number; bodyText: string; timeMs: number }> {
  return page.evaluate(async (emailArg) => {
    const start = performance.now();
    const res = await fetch('/validate-email/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: emailArg }),
    });
    const bodyText = await res.text();
    return { status: res.status, bodyText, timeMs: performance.now() - start };
  }, email);
}

async function getSubmitFormViaFetch(
  page: import('@playwright/test').Page
): Promise<{ status: number }> {
  return page.evaluate(async () => {
    const res = await fetch('/submit-form/', { method: 'GET' });
    return { status: res.status };
  });
}

test.describe('API endpoints, exercised from inside a real page session @api', () => {
  test.beforeEach(async ({ page }) => {
    // Establishing a real page session first is what gets these calls past
    // CloudFront -- a fetch() fired before any page has loaded (or from a
    // context that never navigated) doesn't carry the same signals.
    await page.goto('/inquire/');
  });

  test('API-02 missing required field (Email) -> BUG-07: 502 instead of 4xx @api', async ({
    page,
  }) => {
    const fields = baselineFields();
    delete fields.Email;
    const { status } = await submitFormViaFetch(page, fields);
    // Documents ACTUAL live behavior. Flip to a 4xx expectation once BUG-07
    // is fixed server-side.
    expect(status).toBe(502);
  });

  test('API-03 malformed email -> BUG-08: 502 instead of 4xx @api', async ({ page }) => {
    const fields = { ...baselineFields(), Email: 'not-an-email' };
    const { status } = await submitFormViaFetch(page, fields);
    expect(status).toBe(502);
  });

  test('API-06 GET on submit endpoint -> BUG-09: 502 instead of 405 @api', async ({
    page,
  }) => {
    const { status } = await getSubmitFormViaFetch(page);
    expect(status).toBe(502);
  });

  test('validate-email baseline: valid address -> {valid:true} @api', async ({ page }) => {
    const { status, bodyText } = await validateEmailViaFetch(page, 'karina.zhd+test@gmail.com');
    expect(status).toBe(200);
    const json = JSON.parse(bodyText);
    expect(json).toHaveProperty('valid', true);
  });

  test('API-07 response time p95 over 10 calls (validate-email, non-mutating) @api', async ({
    page,
  }) => {
    const times: number[] = [];
    for (let i = 0; i < 10; i++) {
      const { timeMs, status } = await validateEmailViaFetch(page, 'karina.zhd+test@gmail.com');
      expect(status).toBe(200);
      times.push(timeMs);
    }
    times.sort((a, b) => a - b);
    const p95Index = Math.min(times.length - 1, Math.ceil(0.95 * times.length) - 1);
    const p95 = times[p95Index];
    console.log(`validate-email response times (ms): ${times.map((t) => t.toFixed(0)).join(', ')}`);
    console.log(`p95 (ms): ${p95.toFixed(0)}`);
    expect(p95).toBeLessThan(2000);
  });

  // --- Stubbed contract checks: never touch the real backend. page.route()
  // intercepts /submit-form/ and fulfils with the exact response shape
  // captured live during exploratory testing, so these run safely on every
  // default @api pass with zero risk of creating a real lead. ---

  test('API-01 (stubbed) valid submit -> 2xx, response shape matches contract @api', async ({
    page,
  }) => {
    await page.route('**/submit-form/', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ data: { id: 999999 } }),
      });
    });
    const { status, bodyText } = await submitFormViaFetch(page, baselineFields());
    expect(status).toBeGreaterThanOrEqual(200);
    expect(status).toBeLessThan(300);
    const json = JSON.parse(bodyText);
    expect(json).toHaveProperty('data');
    expect(json.data).toHaveProperty('id');
    expect(typeof json.data.id).toBe('number');
  });

  test('API-04 (stubbed) submit without consent flag -> BUG-06 contract locked in @api', async ({
    page,
  }) => {
    // Stubbed to match the REAL, currently-observed (buggy) behavior
    // captured during exploratory testing: production returns 200 and
    // creates a lead even with no consent field sent at all. See BUG-06 in
    // BUG-REPORT.md for the live evidence (a real lead ID, `126850345`,
    // created with no consent field in the payload) -- this test locks that
    // documented contract in for CI, it does not re-hit production.
    await page.route('**/submit-form/', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ data: { id: 999999 } }),
      });
    });
    const fields = baselineFields();
    delete fields.termsAgreement;
    const { status, bodyText } = await submitFormViaFetch(page, fields);
    expect(status).toBeGreaterThanOrEqual(200);
    expect(status).toBeLessThan(300);
    const json = JSON.parse(bodyText);
    expect(json.data).toHaveProperty('id');
  });

  // API-05 (SQL injection) intentionally omitted here -- not executed
  // against production during this assessment; see postman/collection.json
  // and BUG-REPORT.md for why, and what I'd do with a staging endpoint.
});
